### ISSUE TITLE
virtualenvironment is not supposed to be put on git

### ISSUE THREAD

**Issue by haroonKhan-10p** [Hariss096/todo-djangular#1]
Please add .gitignore and add the folder `venvironment` there.
and I have found usually for most projects that you should keep the folder name to venv.
You might need to run `git rm --cached venvirnonment` to remove it from remote repo.
Please check the syntax.

**Comment by Hariss096** [comment]
.gitignore added. Also, venvironment is removed from the repository as well as commit history and new virtual environment has been created as .venv.
